apiVersion: v1
kind: Pod
metadata:
  name: pod-attacker
  namespace: internet
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        { "name": "internet-net", "interface": "net1", "ips": [ "192.168.0.100/24" ] }
      ]
spec:
  containers:
    - name: attacker
      image: kalilinux/kali-rolling
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      command: ["/bin/bash", "-lc"]
      args:
        - |
          apt update && \
          DEBIAN_FRONTEND=noninteractive apt install -y \
            python3 \
            nmap \
            nikto \
            curl \
            netcat-openbsd \
            gobuster \
            hydra \
            seclists \
            iproute2 \
            iputils-ping \
            net-tools && \

          echo "[init] waiting for net1..." && \
          for i in {1..30}; do ip link show net1 && break || sleep 1; done && \

          ip route replace 10.0.0.0/24 via 192.168.0.253 dev net1 metric 1 && \

          ip addr && \

          ip route get 10.0.0.43 || true && \

          command -v python3 && \
          command -v nmap && \
          command -v nikto && \
          command -v curl && \
          command -v nc && \
          command -v gobuster && \
          command -v hydra && \

          echo "[ready] pod attacker ready; sleeping..." && \
          tail -f /dev/null
      volumeMounts:
        - name: attack-runner-data
          mountPath: /opt
      resources:
        limits:
          memory: "1Gi"
          cpu: "1000m"
  volumes:
    - name: attack-runner-data
      hostPath:
        path: /home/youruser/hr-department/opt
        type: DirectoryOrCreate
