apiVersion: v1
kind: Pod
metadata:
  name: mysql-fi
  namespace: fi
  labels:
    app: mysql-fi
    role: mysqlserver
    department: fi
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "fi-net", "ips": [ "11.0.0.23/24" ] }]'
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "financial"
        - name: MYSQL_USER
          value: "fi"
        - name: MYSQL_PASSWORD
          value: "123123"
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
  volumes:
    - name: mysql-data
      emptyDir: {}
