apiVersion: v1
kind: Pod
metadata:
  name: web-fi
  namespace: fi
  labels:
    app: web-fi
    role: webserver
    department: fi
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "fi-net", "ips": [ "11.0.0.22/24" ] }]'
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
