input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}"
    topics => ["${KAFKA_TOPIC:kafka-topics}"]
    group_id => "${KAFKA_GROUP_ID:kafka-group-example}"
    auto_offset_reset => "latest"
    codec => "json"
  }
}

filter {
  if [@timestamp] and ([@timestamp] =~ /^[0-9.]+$/) {
    mutate {
      remove_field => ["@timestamp"]
    }
  }

  if [event] and [event][original] {
    json {
      source => "[event][original]"
    }

    mutate {
      remove_field => ["[event][original]"]
    }
  }

  if [event_type] == "alert" and [timestamp] {
    date {
      match => ["timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSSSSSZZZ"]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
  } else if [event_type] == "flow" and [flow][start] {
    date {
      match => ["[flow][start]", "yyyy-MM-dd'T'HH:mm:ss.SSSSSSZZZ"]
      target => "@timestamp"
    }
  } else if [timestamp] {
    date {
      match => ["timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSSSSSZZZ"]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
  }

  ruby {
    init => "require 'securerandom'"
    code => "event.set('logstash_uuid', SecureRandom.uuid)"
  }

  if [sonda_id] {
    mutate {
      rename => {
        "sonda_id" => "[kubernetes][pod_name]"
      }
    }
  } else if [kubernetes] and [kubernetes][pod_name] {
    mutate {
      add_field => {
        "[kubernetes][pod_name]" => "%{[kubernetes][pod_name]}"
      }
    }
  } else if [host] and [host][name] {
    mutate {
      add_field => {
        "[kubernetes][pod_name]" => "%{[host][name]}"
      }
    }
  }

  mutate {
    rename => {
      "src_ip"  => "[source][ip]"
      "dest_ip" => "[destination][ip]"
      "proto"   => "[network][transport]"
    }

    add_field => {
      "[event][category]" => "network"
      "[event][kind]"     => "event"
    }
  }

  if [src_port] {
    mutate {
      convert => {
        "src_port" => "integer"
      }
    }
  }

  if [dest_port] {
    mutate {
      convert => {
        "dest_port" => "integer"
      }
    }
  }

  if [tcp] {
    mutate {
      convert => {
        "[tcp][syn]" => "integer"
        "[tcp][ack]" => "integer"
      }
    }
  }

  if [alert][signature] {
  mutate {
    copy => {
      "[alert][signature]" => "alert_signature"
    }
  }

  mutate {
    copy => {
      "[alert][signature]" => "[rule][name]"
     }
   }
 }

  if [alert][severity] {
    mutate {
      convert => {
        "[alert][severity]" => "integer"
      }

      copy => {
        "[alert][severity]" => "[event][severity_value]"
      }
    }

    translate {
      field => "[event][severity_value]"
      destination => "[event][severity]"
      dictionary => {
        "1" => "high"
        "2" => "medium"
        "3" => "low"
      }
      fallback => "unknown"
    }
  }

  if [event_type] {
    mutate {
      copy => {
        "[event_type]" => "event_type_flat"
      }
    }
  }

  if [source][ip] {
    mutate {
      copy => {
        "[source][ip]" => "src_ip_flat"
      }
    }
  }

  if [destination][ip] {
    mutate {
      copy => {
        "[destination][ip]" => "dest_ip_flat"
      }
    }
  }

  if [dns][rrname] {
    mutate {
      copy => {
        "[dns][rrname]" => "dns_rrname"
      }
    }
  }

  if [http][hostname] {
    mutate {
      copy => {
        "[http][hostname]" => "http_hostname"
      }
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  opensearch {
    hosts => ["${OPENSEARCH_HOSTS}"]
    index => "suricata-kafka-%{+YYYY.MM.dd}"

    ssl => true
    ssl_certificate_verification => false

    user => "${OPENSEARCH_USER}"
    password => "${OPENSEARCH_PASSWORD}"

    document_id => "%{logstash_uuid}"
  }
}
