apiVersion: v1
kind: Pod
metadata:
  name: mysql-dev
  namespace: dev
  labels:
    app: mysql-dev
    role: mysqlserver
    department: dev
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "dev-net", "ips": [ "12.0.0.23/24" ] }]'
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "development"
        - name: MYSQL_USER
          value: "dev"
        - name: MYSQL_PASSWORD
          value: "123123"
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
  volumes:
    - name: mysql-data
      emptyDir: {}
