apiVersion: v1
kind: Pod
metadata:
  name: web-dev
  namespace: dev
  labels:
    app: web-dev
    role: webserver
    department: dev
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "dev-net", "ips": [ "12.0.0.22/24" ] }]'
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
