apiVersion: v1
kind: Pod
metadata:
  name: web-hr
  namespace: hr
  labels:
    app: web-hr
    role: webserver
    department: hr
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "hr-net", "ips": [ "10.0.0.22/24" ] }]'
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
