apiVersion: v1
kind: Pod
metadata:
  name: mysql-hr
  namespace: hr
  labels:
    app: mysql-hr
    role: mysqlserver
    department: hr
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "hr-net", "ips": [ "10.0.0.23/24" ] }]'
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "human_resources"
        - name: MYSQL_USER
          value: "hr"
        - name: MYSQL_PASSWORD
          value: "123123"
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
  volumes:
    - name: mysql-data
      emptyDir: {}
