apiVersion: v1
kind: Pod
metadata:
  name: vuln-hr
  namespace: hr
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "hr-net", "ips": [ "10.0.0.43/24" ] }]'
spec:
  restartPolicy: Always
  containers:
    - name: web
      image: nginx:alpine
      ports:
        - containerPort: 80

    - name: sshd
      image: debian:stable-slim
      ports:
        - containerPort: 22
      securityContext:
        runAsUser: 0
      command: ["/bin/sh","-lc","apt-get update && apt-get install -y --no-install-recommends openssh-server ca-certificates && mkdir -p /run/sshd && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && echo 'UsePAM no' >> /etc/ssh/sshd_config && echo 'root:root' | chpasswd && exec /usr/sbin/sshd -D -e"]

    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_ROOT_HOST
          value: "%"
      ports:
        - containerPort: 3306

    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
      ports:
        - containerPort: 5432

    - name: open-ports
      image: alpine:latest
      ports:
        - containerPort: 1433
        - containerPort: 1521
        - containerPort: 5800
        - containerPort: 5810
        - containerPort: 5820
      command:
        - /bin/sh
        - -lc
        - >
          set -e;
          apk add --no-cache socat;
          for p in 1433 1521 5800 5801 5802 5803 5804 5805 5806 5807 5808 5809 5810 5811 5812 5813 5814 5815 5816 5817 5818 5819 5820; do
            echo "listening on $p";
            nohup socat TCP-LISTEN:${p},fork,reuseaddr - >/dev/null 2>&1 &
          done;
          tail -f /dev/null
